### ISSUE TITLE
Some properties not updating

### ISSUE THREAD

**Issue by charlas** [yp87/leaf2mqtt#67]
**Describe the bug**
Some of the properties are not updating (charge levels etc)

**LEAF_TYPE**
NewerThanMay2019

**Expected behavior**
All values to come back.

There seems to be a bug somewhere in the reading battery values for the new leaf's, was working fine, now failing on latest version (46)

FINEST: 2023-09-20 10:26:11.425573: MqttClientWrapper: Publishing message SJNFAAZE1U0173813/climate/json {"cabinTemperatureC":"17.5","cabinTemperatureF":"63.5","RunningStatus":"false","runningStatus":"false","lastReceivedDateTimeUtc":"2023-09-20T09:26:11.424834Z"}
FINEST: 2023-09-20 10:26:12.360993: LeafSession: Executing
FINE: 2023-09-20 10:26:12.619750: LeafSession: RangeError (length): Invalid value: Not in inclusive range 0..3: 4
FINER: 2023-09-20 10:26:12.619879: LeafSession: #0      new NissanConnectBattery (package:dartnissanconnect/src/nissanconnect_battery.dart)
#1      NissanConnectVehicle.requestBatteryStatus (package:dartnissanconnect/src/nissanconnect_vehicle.dart:53)
<asynchronous suspension>
#2      NissanConnectVehicleWrapper.fetchBatteryStatus (file:///app/src/leaf/nissan_connect_wrapper.dart:69)
<asynchronous suspension>
#3      LeafSession._executeWithRetry (file:///app/src/leaf/leaf_session.dart:153)
<asynchronous suspension>
#4      LeafSession.executeWithRetry (file:///app/src/leaf/leaf_session.dart:129)
<asynchronous suspension>
#5      Future.wait.<anonymous closure> (dart:async/future.dart:522)
<asynchronous suspension>
#6      startUpdateLoop (file:///app/src/leaf_2_mqtt.dart:111)
<asynchronous suspension>
#7      Future.wait.<anonymous closure> (dart:async/future.dart:522)
<asynchronous suspension>
#8      main (file:///app/src/leaf_2_mqtt.dart:69)
<asynchronous suspension>
FINE: 2023-09-20 10:26:12.619920: LeafSession: Exception: Execution failed.
FINER: 2023-09-20 10:26:12.619942: LeafSession: #0      LeafSession._executeWithRetry (file:///app/src/leaf/leaf_session.dart:161)
<asynchronous suspension>
#1      LeafSession.executeWithRetry (file:///app/src/leaf/leaf_session.dart:129)
<asynchronous suspension>
#2      Future.wait.<anonymous closure> (dart:async/future.dart:522)
<asynchronous suspension>
#3      startUpdateLoop (file:///app/src/leaf_2_mqtt.dart:111)
<asynchronous suspension>
#4      Future.wait.<anonymous closure> (dart:async/future.dart:522)
<asynchronous suspension>
#5      main (file:///app/src/leaf_2_mqtt.dart:69)
<asynchronous suspension>
WARNING: 2023-09-20 10:26:12.619954: main: Could not execute request.

**Comment by antonhagg** [comment]
Have you investigated this further?
