### ISSUE TITLE
The add-on can get same properties but breaks at same point. 

### ISSUE THREAD

**Issue by marcoaraujo2021** [yp87/leaf2mqtt#68]
Describe the bug
The add-on can get same properties but breaks at same point. 

LEAF_TYPE
NewerThanMay2019

Expected behavior
Finish the Leaf request without any error. 

There seems to be a bug somewhere in the request. Battery values for the new leaf's, was working fine, but the climate for example doesn't work. The request breaks with error. 

Error message: 

FINEST: 2023-10-21 21:33:38.159807: MqttClientWrapper: Publishing message battery/charging false
FINEST: 2023-10-21 21:33:38.159868: MqttClientWrapper: Publishing message battery/cruisingRangeAcOffKm 47
FINEST: 2023-10-21 21:33:38.159923: MqttClientWrapper: Publishing message battery/cruisingRangeAcOffMiles 29
FINEST: 2023-10-21 21:33:38.159978: MqttClientWrapper: Publishing message battery/cruisingRangeAcOnKm 45
FINEST: 2023-10-21 21:33:38.160033: MqttClientWrapper: Publishing message battery/cruisingRangeAcOnMiles 28
FINEST: 2023-10-21 21:33:38.160089: MqttClientWrapper: Publishing message battery/lastUpdatedDateTimeUtc 2023-10-21T16:03:27.000Z
FINEST: 2023-10-21 21:33:38.160169: MqttClientWrapper: Publishing message battery/timeToFullL2InMinutes 8:00:00.000000
FINEST: 2023-10-21 21:33:38.160279: MqttClientWrapper: Publishing message battery/timeToFullL2_6kwInMinutes 0:00:00.000000
FINEST: 2023-10-21 21:33:38.160353: MqttClientWrapper: Publishing message battery/timeToFullTrickleInMinutes 0:00:00.000000
FINEST: 2023-10-21 21:33:38.160417: MqttClientWrapper: Publishing message battery/chargingSpeed ChargingSpeed.NORMAL
FINEST: 2023-10-21 21:33:38.160554: MqttClientWrapper: Publishing message battery/lastReceivedDateTimeUtc 2023-10-21T20:33:38.158095Z
FINEST: 2023-10-21 21:33:38.160657: MqttClientWrapper: Publishing message battery/json {"percentage":"19","connected":"true","charging":"false","cruisingRangeAcOffKm":"47","cruisingRangeAcOffMiles":"29","cruisingRangeAcOnKm":"45","cruisingRangeAcOnMiles":"28","lastUpdatedDateTimeUtc":"2023-10-21T16:03:27.000Z","timeToFullL2InMinutes":"8:00:00.000000","timeToFullL2_6kwInMinutes":"0:00:00.000000","timeToFullTrickleInMinutes":"0:00:00.000000","chargingSpeed":"ChargingSpeed.NORMAL","lastReceivedDateTimeUtc":"2023-10-21T20:33:38.158095Z"}
FINEST: 2023-10-21 21:33:38.160882: MqttClientWrapper: Publishing message XXXXXXXXXXXXXX5565/battery/percentage 19
FINEST: 2023-10-21 21:33:38.161001: MqttClientWrapper: Publishing message XXXXXXXXXXXXXX5565/battery/connected true
FINEST: 2023-10-21 21:33:38.161060: MqttClientWrapper: Publishing message XXXXXXXXXXXXXX5565/battery/charging false
FINEST: 2023-10-21 21:33:38.161122: MqttClientWrapper: Publishing message XXXXXXXXXXXXXX5565/battery/cruisingRangeAcOffKm 47
FINEST: 2023-10-21 21:33:38.161186: MqttClientWrapper: Publishing message XXXXXXXXXXXXXX5565/battery/cruisingRangeAcOffMiles 29
FINEST: 2023-10-21 21:33:38.161247: MqttClientWrapper: Publishing message XXXXXXXXXXXXXX5565/battery/cruisingRangeAcOnKm 45
FINEST: 2023-10-21 21:33:38.161312: MqttClientWrapper: Publishing message XXXXXXXXXXXXXX5565/battery/cruisingRangeAcOnMiles 28
FINEST: 2023-10-21 21:33:38.161368: MqttClientWrapper: Publishing message XXXXXXXXXXXXXX5565/battery/lastUpdatedDateTimeUtc 2023-10-21T16:03:27.000Z
FINEST: 2023-10-21 21:33:38.161493: MqttClientWrapper: Publishing message XXXXXXXXXXXXXX5565/battery/timeToFullL2InMinutes 8:00:00.000000
FINEST: 2023-10-21 21:33:38.161566: MqttClientWrapper: Publishing message XXXXXXXXXXXXXX5565/battery/timeToFullL2_6kwInMinutes 0:00:00.000000
FINEST: 2023-10-21 21:33:38.161637: MqttClientWrapper: Publishing message XXXXXXXXXXXXXX5565/battery/timeToFullTrickleInMinutes 0:00:00.000000
FINEST: 2023-10-21 21:33:38.161706: MqttClientWrapper: Publishing message XXXXXXXXXXXXXX5565/battery/chargingSpeed ChargingSpeed.NORMAL
FINEST: 2023-10-21 21:33:38.161797: MqttClientWrapper: Publishing message XXXXXXXXXXXXXX5565/battery/lastReceivedDateTimeUtc 2023-10-21T20:33:38.158095Z
FINEST: 2023-10-21 21:33:38.161874: MqttClientWrapper: Publishing message XXXXXXXXXXXXXX5565/battery/json {"percentage":"19","connected":"true","charging":"false","cruisingRangeAcOffKm":"47","cruisingRangeAcOffMiles":"29","cruisingRangeAcOnKm":"45","cruisingRangeAcOnMiles":"28","lastUpdatedDateTimeUtc":"2023-10-21T16:03:27.000Z","timeToFullL2InMinutes":"8:00:00.000000","timeToFullL2_6kwInMinutes":"0:00:00.000000","timeToFullTrickleInMinutes":"0:00:00.000000","chargingSpeed":"ChargingSpeed.NORMAL","lastReceivedDateTimeUtc":"2023-10-21T20:33:38.158095Z"}
FINEST: 2023-10-21 21:33:38.171469: main: publishStates {cockpitStatus/totalMileage: 111487, cockpitStatus/lastReceivedDateTimeUtc: 2023-10-21T20:33:38.171402Z, cockpitStatus/json: {"totalMileage":"111487","lastReceivedDateTimeUtc":"2023-10-21T20:33:38.171402Z"}, cockpit/totalMileage: 111487, cockpit/lastReceivedDateTimeUtc: 2023-10-21T20:33:38.171402Z, cockpit/json: {"totalMileage":"111487","lastReceivedDateTimeUtc":"2023-10-21T20:33:38.171402Z"}, XXXXXXXXXXXXXX5565/cockpitStatus/totalMileage: 111487, XXXXXXXXXXXXXX5565/cockpitStatus/lastReceivedDateTimeUtc: 2023-10-21T20:33:38.171402Z, XXXXXXXXXXXXXX5565/cockpitStatus/json: {"totalMileage":"111487","lastReceivedDateTimeUtc":"2023-10-21T20:33:38.171402Z"}, XXXXXXXXXXXXXX5565/cockpit/totalMileage: 111487, XXXXXXXXXXXXXX5565/cockpit/lastReceivedDateTimeUtc: 2023-10-21T20:33:38.171402Z, XXXXXXXXXXXXXX5565/cockpit/json: {"totalMileage":"111487","lastReceivedDateTimeUtc":"2023-10-21T20:33:38.171402Z"}}
FINEST: 2023-10-21 21:33:38.171549: MqttClientWrapper: Publishing message cockpitStatus/totalMileage 111487
FINEST: 2023-10-21 21:33:38.171918: MqttClientWrapper: Publishing message cockpitStatus/lastReceivedDateTimeUtc 2023-10-21T20:33:38.171402Z
FINEST: 2023-10-21 21:33:38.172113: MqttClientWrapper: Publishing message cockpitStatus/json {"totalMileage":"111487","lastReceivedDateTimeUtc":"2023-10-21T20:33:38.171402Z"}
FINEST: 2023-10-21 21:33:38.172261: MqttClientWrapper: Publishing message cockpit/totalMileage 111487
FINEST: 2023-10-21 21:33:38.172354: MqttClientWrapper: Publishing message cockpit/lastReceivedDateTimeUtc 2023-10-21T20:33:38.171402Z
FINEST: 2023-10-21 21:33:38.172458: MqttClientWrapper: Publishing message cockpit/json {"totalMileage":"111487","lastReceivedDateTimeUtc":"2023-10-21T20:33:38.171402Z"}
FINEST: 2023-10-21 21:33:38.172589: MqttClientWrapper: Publishing message XXXXXXXXXXXXXX5565/cockpitStatus/totalMileage 111487
FINEST: 2023-10-21 21:33:38.172683: MqttClientWrapper: Publishing message XXXXXXXXXXXXXX5565/cockpitStatus/lastReceivedDateTimeUtc 2023-10-21T20:33:38.171402Z
FINEST: 2023-10-21 21:33:38.172814: MqttClientWrapper: Publishing message XXXXXXXXXXXXXX5565/cockpitStatus/json {"totalMileage":"111487","lastReceivedDateTimeUtc":"2023-10-21T20:33:38.171402Z"}
FINEST: 2023-10-21 21:33:38.173032: MqttClientWrapper: Publishing message XXXXXXXXXXXXXX5565/cockpit/totalMileage 111487
FINEST: 2023-10-21 21:33:38.173569: MqttClientWrapper: Publishing message XXXXXXXXXXXXXX5565/cockpit/lastReceivedDateTimeUtc 2023-10-21T20:33:38.171402Z
FINEST: 2023-10-21 21:33:38.173688: MqttClientWrapper: Publishing message XXXXXXXXXXXXXX5565/cockpit/json {"totalMileage":"111487","lastReceivedDateTimeUtc":"2023-10-21T20:33:38.171402Z"}
FINE: 2023-10-21 21:33:40.097003: LeafSession: NoSuchMethodError: The method '[]' was called on null.
Receiver: null
Tried calling: []("attributes")
FINER: 2023-10-21 21:33:40.097115: LeafSession: #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38)
#1      _objectNoSuchMethod (dart:core-patch/object_patch.dart:85)
#2      NissanConnectVehicle.requestLocation (package:dartnissanconnect/src/nissanconnect_vehicle.dart:267)
<asynchronous suspension>
#3      NissanConnectVehicleWrapper.fetchLocation (file:///app/src/leaf/nissan_connect_wrapper.dart:119)
<asynchronous suspension>
#4      LeafSession._executeWithRetry (file:///app/src/leaf/leaf_session.dart:153)
<asynchronous suspension>
#5      LeafSession.executeWithRetry (file:///app/src/leaf/leaf_session.dart:129)
<asynchronous suspension>
#6      Future.wait.<anonymous closure> (dart:async/future.dart:522)
<asynchronous suspension>
#7      startUpdateLoop (file:///app/src/leaf_2_mqtt.dart:111)
<asynchronous suspension>
#8      Future.wait.<anonymous closure> (dart:async/future.dart:522)
<asynchronous suspension>
#9      main (file:///app/src/leaf_2_mqtt.dart:69)
<asynchronous suspension>

FINER: 2023-10-21 21:33:40.097126: LeafSession: Force a login before retrying failed execution.
FINE: 2023-10-21 21:33:40.860955: LeafSession: NoSuchMethodError: The method '*' was called on null.
Receiver: null
Tried calling: *()
FINER: 2023-10-21 21:33:40.861201: LeafSession: #0      ClimateInfoBuilder.withCabinTemperatureCelsius (file:///app/src/leaf/builder/leaf_climate_builder.dart:12)
#1      NissanConnectVehicleWrapper.fetchClimateStatus (file:///app/src/leaf/nissan_connect_wrapper.dart:102)
<asynchronous suspension>
#2      LeafSession._executeWithRetry (file:///app/src/leaf/leaf_session.dart:153)
<asynchronous suspension>
#3      LeafSession.executeWithRetry (file:///app/src/leaf/leaf_session.dart:129)
<asynchronous suspension>
#4      Future.wait.<anonymous closure> (dart:async/future.dart:522)
<asynchronous suspension>
#5      startUpdateLoop (file:///app/src/leaf_2_mqtt.dart:111)
<asynchronous suspension>
#6      Future.wait.<anonymous closure> (dart:async/future.dart:522)
<asynchronous suspension>
#7      main (file:///app/src/leaf_2_mqtt.dart:69)
<asynchronous suspension>

FINER: 2023-10-21 21:33:40.861225: LeafSession: Force a login before retrying failed execution.
FINE: 2023-10-21 21:33:42.396340: LeafSession: LateInitializationError: Field 'vehicles' has not been initialized.
FINER: 2023-10-21 21:33:42.396573: LeafSession: #0      NissanConnectSessionWrapper.login (file:///app/src/leaf/nissan_connect_wrapper.dart)
<asynchronous suspension>
#1      LeafSession._executeWithRetry (file:///app/src/leaf/leaf_session.dart:146)
<asynchronous suspension>
#2      LeafSession.executeWithRetry (file:///app/src/leaf/leaf_session.dart:129)
<asynchronous suspension>
#3      Future.wait.<anonymous closure> (dart:async/future.dart:522)
<asynchronous suspension>
#4      startUpdateLoop (file:///app/src/leaf_2_mqtt.dart:111)
<asynchronous suspension>
#5      Future.wait.<anonymous closure> (dart:async/future.dart:522)
<asynchronous suspension>
#6      main (file:///app/src/leaf_2_mqtt.dart:69)
<asynchronous suspension>

FINEST: 2023-10-21 21:33:42.396599: LeafSession: Executing
FINEST: 2023-10-21 21:33:42.723356: LeafSession: Executing

**Comment by cpaius** [comment]
Getting same error. Did not manage to find what is causing it as there is not much logging around that section of code.
